line-length = 320

output-format = "full"

target-version = "py312"

[lint]
select = [
    "B",
    "C4",
    "COM818",
    "G",
    "E",
    "EXE",
    "F",
    "SIM1",
    "Q004",
    "W",
    # Not included in flake8
    "I",
    "NPY",
    "PERF",
    "PGH004",
    "PIE794",
    "PIE800",
    "PIE804",
    "PIE807",
    "PIE810",
    "PLC0131", # type bivariance
    "PLC0132", # type param mismatch
    "PLC0205", # string as __slots__
    "PLE",
    "PLR0206", # property with params
    "PLR1722", # use sys exit
    "PLW0129", # assert on string literal
    "PLW0406", # import self
    "PLW0711", # binary op exception
    "PLW1509", # preexec_fn not safe with threads
    "PLW3301", # nested min max
    "PT006", # TODO: enable more PT rules
    "PT022",
    "PT023",
    "PT024",
    "PT025",
    "PT026",
    "RUF008", # mutable dataclass default
    "RUF016", # type error non-integer index
    "RUF017",
    "TRY302",
]

ignore = [
    # these ignores are from flake8-bugbear; please fix!
    "B007", "B008", "B017",
    "B018", # Useless expression
    "B019",
    "B020",
    "B023",
    "B028", # No explicit `stacklevel` keyword argument found
    "B904",
    "B905",
    "C408", # C408 ignored because we like the dict keyword argument syntax
    "COM812", # conflict with formatter!
    "COM819", # conflict with formatter!
    "D206", # conflict with formatter!
    "D300", # conflict with formatter!
    "E111", # conflict with formatter!
    "E114", # conflict with formatter!
    "E117", # conflict with formatter!
    "E402",
    "E501", # Never use it!
    "E721",
    "E731", # Assign lambda expression
    "E741",
    "EXE001",
    "F401", # unused-import
    "F403", # undefined-local-with-import-star
    "F405",
    "F821", # undefined-name
    "F841",
    # these ignores are from flake8-logging-format; please fix!
    "G101",
    "ISC001", # conflict with formatter!
    "ISC002", # conflict with formatter!
    "Q000", # conflict with formatter!
    "Q001", # conflict with formatter!
    "Q002", # conflict with formatter!
    "Q003", # conflict with formatter!
    "W191", # conflict with formatter!
    # these ignores are from ruff NPY; please fix!
    "NPY002",
    # these ignores are from ruff PERF; please fix!
    "PERF203",
    "PERF401",
    "PERF403",
    # these ignores are from PYI; please fix!
    "PYI019",
    "PYI024",
    "PYI036",
    "PYI041",
    "PYI056",
    "SIM102", "SIM103", "SIM112", # flake8-simplify code styles
    "SIM105", # these ignores are from flake8-simplify. please fix or ignore with commented reason
    "SIM108",
    "SIM110",
    "SIM114", # Combine `if` branches using logical `or` operator
    "SIM115",
    "SIM116", # Disable Use a dictionary instead of consecutive `if` statements
    "SIM117",
    "SIM118",
]

[lint.isort]
case-sensitive = true
combine-as-imports = true
order-by-type = false

[format]
docstring-code-format = true
docstring-code-line-length = "dynamic"
indent-style = "space"
line-ending = "lf"
preview = true
quote-style = "single"
skip-magic-trailing-comma = false
